updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    exclude-paths:
      - ".github/workflows/*.lock.yml" # gh aw managed workflows
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
version: 2
