#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apk:
  fonts:
    packages:
      fontconfig: 2.15.0-r1
      ttf-dejavu: 2.37-r5
    description: |
      java.lang.UnsatisfiedLinkError: libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
      java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
      https://github.com/docker-library/openjdk/pull/235#issuecomment-424466077
  cacerts:
    packages:
      ca-certificates: 20240705-r0
      p11-kit-trust: 0.25.3-r0
    description: |
      utilities for keeping Alpine and OpenJDK CA certificates in sync
      https://github.com/adoptium/containers/issues/293
  locales:
    packages:
       musl-locales: 0.1.0-r1
       musl-locales-lang: 0.1.0-r1
    description: |
      locales ensures proper character encoding and locale-specific behaviors using en_US.UTF-8
  binutils:
    packages:
      binutils: 2.42-r0
    version: 17
    version_operator: '>='
    description: |
      jlink --strip-debug on 13+ needs objcopy: https://github.com/docker-library/openjdk/issues/351
      Error: java.io.IOException: Cannot run program "objcopy": error=2, No such file or directory
  tzdata:
    packages:
      tzdata: 2024a-r1
  coreutils:
    packages:
      coreutils: 9.5-r1
    description: |
      Contains `csplit` used for splitting multiple certificates in one file to multiple files, since keytool can
      only import one at a time.
  openssl:
    packages:
      openssl: 3.3.1-r3
    description: |
      Needed to extract CN and generate aliases for certificates
