name: Jinja CI
on:
  pull_request:
    paths:
      - adoptium_api.py
      - dockerhub_doc_config_update.py
      - eol_checker.py
      - generate_dockerfiles.py
      - test_dockerhub_doc_config_update.py
      - test_eol_checker.py
      - test_generate_dockerfiles.py
      - requirements.txt
    branches: [ main ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: "pip3 install -r requirements.txt"

      - name: Run tests
        run: python3 -m unittest discover -v -p 'test_*.py'
