name: Dependabot auto-merge
on: pull_request_target

permissions: read-all

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: adoptium/.github/.github/workflows/dependabot-auto-merge.yml@main
