name: Scan

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  scan:
    name: Scan Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.7.0
        with:
          scan-type: 'config'
          trivy-config: .github/trivy.yaml

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'scan_dockerfile_result.sarif'

      - name: Archive scan results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: trivyResult
          path: 'scan_dockerfile_result.sarif'
          if-no-files-found: error
